general:
  bootstrap_end_time: 300
  stop_time: 3600
  progress: true
  template_directory: shadow.data.template
network:
  use_shortest_path: false
  graph:
    type: gml
    file:
      path: /tordata/tornettools/experiment0-0.0001/conf/atlas_v201801.shadow_v2.gml.xz
      compression: xz
hosts:
  4uthority1:
    network_node_id: 49
    ip_addr: 100.0.0.1
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority1 --Nickname 4uthority1 --defaults-torrc torrc-defaults -f torrc
      start_time: 1
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
  4uthority2:
    network_node_id: 1151
    ip_addr: 100.0.0.2
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority2 --Nickname 4uthority2 --defaults-torrc torrc-defaults -f torrc
      start_time: 1
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
  4uthority3:
    network_node_id: 327
    ip_addr: 100.0.0.3
    bandwidth_down: 1000000 kilobit
    bandwidth_up: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority3 --Nickname 4uthority3 --defaults-torrc torrc-defaults -f torrc
      start_time: 1
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 2
  relay1exitguard:
    network_node_id: 1085
    ip_addr: 54.37.19.84
    bandwidth_down: 138592 kilobit
    bandwidth_up: 138592 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay1exitguard --Nickname relay1exitguard --defaults-torrc torrc-defaults -f torrc
      start_time: 2
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 3
  relay2exit:
    network_node_id: 732
    ip_addr: 178.165.72.177
    bandwidth_down: 74944 kilobit
    bandwidth_up: 74944 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay2exit --Nickname relay2exit --defaults-torrc torrc-defaults -f torrc
      start_time: 3
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 4
  relay3guard:
    network_node_id: 2505
    ip_addr: 5.135.199.13
    bandwidth_down: 110208 kilobit
    bandwidth_up: 110208 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay3guard --Nickname relay3guard --defaults-torrc torrc-defaults -f torrc
      start_time: 4
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 5
  relay4middle:
    network_node_id: 503
    ip_addr: 107.189.11.123
    bandwidth_down: 8832 kilobit
    bandwidth_up: 8832 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay4middle --Nickname relay4middle --defaults-torrc torrc-defaults -f torrc
      start_time: 5
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 6
  myMarkovClient1:
    network_node_id: 9999
    ip_addr: 102.0.0.11
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient1 --Nickname myMarkovClient1 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions1.csv
      start_time: 1800
  myMarkovClient2:
    network_node_id: 9999
    ip_addr: 102.0.0.12
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient2 --Nickname myMarkovClient2 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions2.csv
      start_time: 1800
  myMarkovClient3:
    network_node_id: 9999
    ip_addr: 102.0.0.13
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient3 --Nickname myMarkovClient3 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions3.csv
      start_time: 1800
  myMarkovClient4:
    network_node_id: 9999
    ip_addr: 102.0.0.14
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient4 --Nickname myMarkovClient4 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions4.csv
      start_time: 1800
  myMarkovClient5:
    network_node_id: 9999
    ip_addr: 102.0.0.15
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient5 --Nickname myMarkovClient5 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions5.csv
      start_time: 1800
  myMarkovClient6:
    network_node_id: 9999
    ip_addr: 102.0.0.16
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient6 --Nickname myMarkovClient6 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions6.csv
      start_time: 1800
  myMarkovClient7:
    network_node_id: 9999
    ip_addr: 102.0.0.17
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient7 --Nickname myMarkovClient7 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions7.csv
      start_time: 1800
  myMarkovClient8:
    network_node_id: 9999
    ip_addr: 102.0.0.18
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient8 --Nickname myMarkovClient8 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions8.csv
      start_time: 1800
  myMarkovClient9:
    network_node_id: 9999
    ip_addr: 102.0.0.19
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient9 --Nickname myMarkovClient9 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions9.csv
      start_time: 1800
  myMarkovClient10:
    network_node_id: 9999
    ip_addr: 102.0.0.20
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address myMarkovClient10 --Nickname myMarkovClient10 --defaults-torrc torrc-defaults -f torrc
      environment: OPENBLAS_NUM_THREADS=1
      start_time: 240
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 241
    - path: /tordata/config/pythonSocks.py
      args: /tordata/config/user_actions10.csv
      start_time: 1800
  myMarkovServer:
    network_node_id: 9999
    ip_addr: 101.0.0.10
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: /tordata/config/pythonServer.py
      start_time: 500
experimental:
  host_heartbeat_interval: 1 min
  host_heartbeat_log_info:
  - node
  - socket
  - ram
host_defaults:
  pcap_directory: .
